# Generated by Django 4.1.4 on 2023-01-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access_records',
            old_name='nmae',
            new_name='name',
        ),
    ]
